package com.predictifylabs.backend.application.ports.output;

/**
 * Output port for AI text generation.
 * Defines the contract that any AI adapter must fulfill (Gemini, OpenAI, etc.)
 */
public interface AiGeneratorPort {

    /**
     * Generates text based on a given prompt.
     *
     * @param prompt The input text for the AI
     * @return The text generated by the AI
     */
    String generateText(String prompt);
}
